### ISSUE TITLE
Assertion bug in 0.1.21

### ISSUE THREAD

**Issue by JulsKawa** [warthog-network/Warthog#37]
```
 [2024-01-25 19:34:01.535] [error] data(c).fork_iter()->first=9, fr.lower()=1
Assertion failed: data(c).fork_iter()->first == fr.lower() (../../code/src/node/eventloop/sync/block_download/block_download.cpp: do_probe_requests: 216) 
```

**Comment by ByPumbaa** [comment]
Please report whether v0.1.22 still has this issue.

**Comment by ByPumbaa** [comment]
Thank you indeed I also suspect this. It is just really strange because we protected the access with classes that guarantee that the two quantities in the assert should always be equal, we will continue with investigation. Thank you.
