### ISSUE TITLE
Mining API bug

### ISSUE THREAD

**Issue by JulsKawa** [warthog-network/Warthog#38]
![image](https://github.com/warthog-network/Warthog/assets/24568624/a96ff248-7ac4-453d-8f95-7aecff08c69e)

Last version of the miner / node.

Bug reported by IronGrip

**Comment by andrewcrypto777** [comment]
Please ask him to attach the output of:
`wget -S -O - <ip:port>/chain/mine/<wallet address>/log`

**Comment by ByPumbaa** [comment]
Is this bug still present?
